name: Homebrew Tap Test
on: [push]
jobs:
  test-tap:
    runs-on: macos-11
    steps:
      - name: Homebrew Tap
        run: |
          brew update
          brew tap finfet/kestrel
          brew install kestrel-cli
          kestrel-cli --version
