name: Homebrew Tap Test
on: [push]
jobs:
  test-tap:
    runs-on: macos-latest
    steps:
      - name: Homebrew Tap
        run: |
          brew update
          brew tap finfet/kestrel
          brew install finfet/kestrel/kestrel-cli
          kestrel --version
